Table cidade {
  id int [pk, increment]
  nome varchar(250) [not null, unique, note: 'Nome']
  Note: 'Cidade'
}

Table cliente {
  id int [pk, increment]
  data_de_nascimento date [not null, note: 'Data de Nascimento']
  email varchar(250) [not null, unique, note: 'Email']
  password text [not null, note: 'password']
  primeiro_nome varchar(250) [not null, note: 'Primeiro Nome']
  ultimo_nome varchar(250) [not null, note: 'Ultimo Nome']
  Note: 'Cliente'
}

Table codigo_postal {
  id int [pk, increment]
  cidade_id int [not null, ref: > cidade.id, note: 'cidade']
  codigo varchar(250) [not null, unique, note: 'codigo']
  rua varchar(250) [not null, note: 'rua']
  Note: 'CodigoPostal'
}

Table encomenda {
  id int [pk, increment]
  andar varchar(250) [not null, note: 'andar']
  cliente_id int [not null, ref: > cliente.id, note: 'cliente']
  codigo_postal_id int [not null, ref: > codigo_postal.id, note: 'codigo_postal']
  data_entrega timestamp [note: 'DataDeEntrega']
  descricao text [not null, note: 'descricao']
  estado_id int [not null, ref: > encomenda_estado.id, note: 'estado']
  estafeta_id int [ref: > estafeta.id, note: 'Estafeta']
  latitude numeric(30, 14) [not null, note: 'Latitude']
  longitude numeric(30, 14) [not null, note: 'Longitude']
  motivo_rejeicao varchar(250) [note: 'MotivoRejeicao']
  observacoes text [note: 'observacoes']
  pagamento_id int [not null, ref: > pagamento.id, note: 'pagamento']
  porta varchar(250) [not null, note: 'porta']
  preco real [not null, note: 'preco']
  telefone varchar(250) [not null, note: 'telefone']
  Note: 'Encomenda'
}

Table encomenda_estado {
  id int [pk, increment]
  nome varchar(250) [not null, unique, note: 'Nome']
  Note: 'Estado'
}

Table estafeta {
  id int [pk, increment]
  data_nascimento date [not null, note: 'DataNascimento']
  estado_id int [not null, ref: > estafeta_estado.id, note: 'Estado']
  latitude numeric(30, 14) [note: 'Latitude']
  longitude numeric(30, 14) [note: 'Longitude']
  matricula varchar(250) [not null, unique, note: 'Matricula']
  nome varchar(250) [not null, note: 'Nome']
  telefone varchar(250) [not null, note: 'Telefone']
  veiculo_id int [not null, ref: > estafeta_veiculo.id, note: 'Veiculo']
  Note: 'Estafeta'
}

Table estafeta_estado {
  id int [pk, increment]
  nome varchar(250) [not null, note: 'Nome']
  Note: 'Estado'
}

Table estafeta_veiculo {
  id int [pk, increment]
  nome varchar(250) [not null, note: 'Nome']
  velocidade int [note: 'Velocidade']
  Note: 'Veículo'
}

Table operador {
  id int [pk, increment]
  data_de_nascimento date [not null, note: 'Data de Nascimento']
  email varchar(250) [not null, unique, note: 'Email']
  password text [not null, note: 'password']
  primeiro_nome varchar(250) [not null, note: 'Primeiro Nome']
  ultimo_nome varchar(250) [not null, note: 'Ultimo Nome']
  Note: 'Operador'
}

Table pagamento {
  id int [pk, increment]
  nome varchar(250) [not null, unique, note: 'Nome']
  Note: 'Pagamento'
}

